### ISSUE TITLE
User Functions not available in TYPO3 7.6 LTS

### ISSUE THREAD

**Issue by onlinenow** [carstenwindler/cwmobileredirect#4] opened 2017-01-26 14:44 UTC
I upgraded a project from TYPO3 4.5 LTS to 7.6 LTS and i noticed that the user functions user_isMobileForced etc. are not available. My guess that including the class file with the functions by the class loader is not enough to make them available. 

My workaround is to remove the functions from the Main.php and put them in a seperate file. Then i added a require_once call to this file in the ext_localconf.php.

**Comment by carstenwindler** [comment] 2017-01-27 21:58
Thanks for reporting this. 4.5 to 7.6 is quite some jump, by the way.

It's been a while since I last worked with Typo3, to be honest. Looking at the code now I would say the user functions never worked since I made it version 7 compatible, since they just moved into the extensions namespace. Probably you are the only one out there using this feature :-)

Please allow me some time to reproduce this, I need to set up a test Typo3 instance etc.

**Comment by carstenwindler** [comment] 2017-01-29 22:19
Would you pls give this branch a try? https://github.com/carstenwindler/cwmobileredirect/tree/issues/4

According to https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/UserAndUserInt/Index.html
this
`CarstenWindler\Cwmobileredirect\Main->user_isMobileForced`
could/should work. The build currently fails because user_isMobileForced is not a valid name anymore, but let's ignore that at the moment.

**Comment by onlinenow** [comment] 2017-01-30 09:34
This does not work, sorry. I am using the user functions in a TypoScript condition and the TYPO3 core code for this does not load classes or anything. Its just tests if the give function is callable. Even if this would work, its a breaking change and people would need to update their TypoScript.

I created a pull request with the changes i made to get it working again.

**Comment by carstenwindler** [comment] 2017-01-30 09:42
Awesome, thanks! Would you mind solving the Code Sniffer issues? I'll merge it then.

**Comment by onlinenow** [comment] 2017-01-30 09:59
Fixed the sniffer issues.

**Comment by carstenwindler** [comment] 2017-01-30 10:06
Thanks, merged.

**Closed by carstenwindler** 2017-01-30 10:06 UTC
